### PR TITLE
Enforce SameSite=Strict

### PR DESCRIPTION
**Pull request by diamondburned**
This adds additional guard into the JWT cookie so that it does not leak on cross-origin requests.

Related issue: https://github.com/LemmyNet/lemmy/pull/3301

### CODE REVIEW

**Comment by diamondburned** [comment]
It's worth mentioning that this PR completely rips out `isomorphic-cookie` and replaces it with code that directly uses `document.cookie`. This keeps the same exact behavior as before, since the library never used the cookie in the backend anyway. All cookie-setting was done in the frontend!

**Review by SleeplessOne1917 — APPROVED** [review]
@alectrocute @dessalines @jsit I wonder if this will also solve the user cache busting bug?

**Comment by alectrocute** [comment]
@SleeplessOne1917 Good point.

Can we use this to fix the inoperable `user.auth()` conditional on `middleware.ts` as well?

**Comment by SleeplessOne1917** [comment]
> Can we use this to fix the inoperable user.auth() conditional on middleware.ts as well?

I think so. I'll do it in a separate PR when I get the chance.

**Review by alectrocute — APPROVED** [review]
Nice.

**Pull request merged**
