### PR TITLE
Fixing copy suggested title when creating posts.

### PR DESCRIPTION
**Pull request by dessalines**
I have no idea why, but these `onBlur` events broke the onClick for copy suggested title.

What are they doing exactly?

### CODE REVIEW

**Review by SleeplessOne1917 — CHANGES_REQUESTED** [review]
The `onBlur`s set the url query params when the user clicks outside of the inputs or if the inputs use focus. The alternative is updating them every time they are changed (basically every time the user adds or removes a character while typing in the field), which seems overkill.

Removing all of these will break the create post query param regression fix I did last night. I'll take a look at this now.

**Comment by dessalines** [comment]
Sweet, thx.

**Comment by matc-pub** [comment]
@SleeplessOne1917  I think the problem is that the state is lost every time the url updates. `CreatePost` doesn't have a `mountedSameRouteNavKey` in `src/shared/routes.ts`.

**Comment by dessalines** [comment]
I've removed the lemmy-ui `0.19.4` tag until we get that one fixed, last hour bug. 

If you can't figure this out, is removing these onBlurs breaking anything? Or is it just wasteful.

**Comment by SleeplessOne1917** [comment]
I figured out the problem. I'm gonna clean things up a bit and open a PR.

**Comment by dessalines** [comment]
Cool, I'll close this one then.

**Pull request closed without merging**
