### PR TITLE
fix: Re-arrange elements beneath markdown textarea #1057

### LINKED ISSUE #1057: Language drop-down for comments is clipped
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

Language drop-down for comments is clipped until you interact with it. May be mobile only. Spawned from #1047 

### Steps to Reproduce

1. Open any Lemmy post on mobile

Screenshot_20230531-224245~3

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
- What OS are you trying to install lemmy on?
- Any browser console errors?

Android Chrome on Pixel 7 pro

### PR DESCRIPTION
**Pull request by jsit**
Fixes #1057

## Before:
Screenshot 2023-06-14 at 5 41 54 PM

## After:

Screenshot 2023-06-04 at 4 04 28 PM

### CODE REVIEW

**Comment by SleeplessOne1917** [comment]
This is something I'd need user feedback on, since your code seems fine but I don't think I can make the best evaluation of the UX.

**Comment by Nutomic** [comment]
How about moving the formatting buttons on top of the text field? That seems more common on other sites.

**Comment by jsit** [comment]
@Nutomic @alectrocute I had this thought too, but making that change felt outside of the scope of this bug. Would be happy to do it in another PR as an "enhancement".

**Review by SleeplessOne1917 — APPROVED** [review]
If you'll do an enhancement PR later, this is fine for now.

**Review by dessalines — APPROVED** [review]

**Pull request merged**
