### PR TITLE
Changing sameSite cookie from Strict to Lax.

### LINKED ISSUE #2601: Inbox doesn't work if it's the first page to be viewed
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you start at the homepage then use the inbox button, then it works.

If you start with the inbox URL (e.g. when clicking the "inbox" link in an email), then it asks you to log in.

### Steps to Reproduce

1. Go to a new browser tab that doesn't already have Lemmy open
2. Go directly to the /inbox URL

### Technical Details

Safari from iOS 17.5.1

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

https://lemmy.ca

### LINKED ISSUE #2666: [Bug] reloading page loggs you out of your account
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If I reload any page the page reloads but I am not logged in any more. Weirdly enough the only appears to be an issue on one of my PCs. I've disabled all browser extensions to make sure nothing is interfering. I can't reproduce the issue on my laptop, despite being basically the same setup as the afflicted one, but on this one computer it always happens. 

### Steps to Reproduce

1. log in to your account
2. press f5 on your keyboard

### Technical Details

Project Bluefin (Fedora Atomic with some additional tweaks)
Firefox Flatpak 129.0.1 (64-Bit)

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

feddit.org

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #2666
- Fixes #2601

See the above issues for context.

### CODE REVIEW

**Review by SleeplessOne1917 — APPROVED** [review]
This should fix #2601, but I don't know if it will work for #2666. The latter seems Firefox specific. Once this is merged and reaches a staging environment, it should be tested on non-FF browsers like Chrome or Safari.

**Comment by dessalines** [comment]
Once these PRs are merged, I'll start another beta.

**Comment by couladin** [comment]
> ...don't know if it will work for #2666 

Just flushed my cookies and tried logging in (2FA enabled). It doesn't fix the issue: logs in fine, scrolling is disabled, and a refresh (^R or F5) logs me out again.

Using Firefox with Enhanced Tracking Protection in a Firefox multi-account container, uBlock and a network adblocker (AdGuard Home). The latter two don't flag anything unusual.

**Comment by dessalines** [comment]
@couladin you used 0.19.6-beta.7 on voyager.lemmy.ml, right?

**Comment by couladin** [comment]
@dessalines I'm using https://lemmy.world/c/voyagerapp (no idea what voyager.lemmy.ml is, sorry). Voyager 2.17.0 (via F-Droid) and Firefox Mobile 129.0.2 (via Play Store) work fine, both on the same device.

I've only seen this with my account on `lemmynsfw.com` - my account on `lemmy.world` (technically `old.lemmy.world`) is unaffected.

This is what I wrote elsewhere recently, thinking it might be an issue specific to lemmynsfw:

> It was logged out when I visited today on Firefox in Linux, so I did the usual (close tab, clear cookies, checked adblocker logs) and the behaviour remains: first visit is logged out but otherwise normal, logging in works but all scrolling is disabled, hitting refresh logs me out again.

This impacts Firefox 129.0.2 desktop on Linux (Arch variant), and on the same network as the above mobile device.

**Comment by SleeplessOne1917** [comment]
> no idea what voyager.lemmy.ml is

That's a test instance that gets used to beta test new versions of Lemmy before being used in production across other instances. It's unfortunate that it shares a name with one of the most popular Lemmy frontends.

> I've only seen this with my account on lemmynsfw.com - my account on lemmy.world (technically old.lemmy.world) is unaffected.

Were you already logged in to lemmy.world and not already logged into lemmynsfw.com when upgrading to Firefox 129? I noticed that the issue didn't happen for machines I was already logged in on, but it did happen after logging in on a machine after the Firefox update.

**Comment by dessalines** [comment]
@couladin when we merge PRs, that fix doesn't instantly get pushed to every lemmy instance. We usually push them to a test instance like voyager.lemmy.ml , to make sure the fix worked.

**Comment by couladin** [comment]
@SleeplessOne1917 Yes, an unfortunate naming coincidence. :) I was logged into both, but they weren't open during the process, though I use Firefox Multi-Account Containers on desktop and the two servers are in different ones.

@dessalines A test server makes sense. Wasn't aware that's what voyager is, but it's good to know.

Please let me know if you need any more data or testing tasks that may help narrow it down.

**Comment by dessalines** [comment]
No probs, ya just let me know if you need me to approve a test account there, we desperately need testers  :)

**Pull request merged**
