### PR TITLE
Feature add three six and nine months options frontend

### PR DESCRIPTION
**Pull request by c-andy-candies**
I adapted the code from #1345 to add the sorting options for 3, 6 and 9 months which I think would be very cool to have, as someone pointed out here LemmyNet/lemmy#3217 

As the original PR I also am currently doing PRs for backend and translations.

LemmyNet/lemmy#3226

LemmyNet/lemmy-translations#69

This is my first contribution so please forgive me if I did something wrong.

### CODE REVIEW

**Comment by dessalines** [comment]
Once the back-end gets merged, I'll do a lemmy-js-client release so you can add this.

**Comment by dessalines** [comment]
Okay this should be up now, `lemmy-js-client: 0.18.1-rc.1`

**Comment by L3v3L** [comment]
this should be blocked until my comments on https://github.com/LemmyNet/lemmy/pull/3226 have been addressed.

**Comment by c-andy-candies** [comment]
I think all comments have been addressed, do I need to do something else here?

**Comment by L3v3L** [comment]
I think you need to make woodpecker pass

**Review by SleeplessOne1917 — APPROVED** [review]
Should be good to merge once the merge conflicts are resolved and woodpecker cooperates.

**Comment by c-andy-candies** [comment]
So sorry, I made a mistake, I closed it, should I do a new one?

**Comment by SleeplessOne1917** [comment]
Github isn't letting me reopen it and this PR shows 0 files changed, so I think you will need to open a new one.

**Comment by c-andy-candies** [comment]
Reopening

**Comment by c-andy-candies** [comment]
Done #1689

**Pull request closed without merging**
