### PR TITLE
fix: Add data-bs-theme attribute for user dark/light modes

### LINKED ISSUE #1774: Upload image buttons use white theme even on a dark one
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Looks like this:
image

### Steps to Reproduce

1. Use a dark theme
2. Click "Create post"
3. Look

### Technical Details

Firefox 114

Likely regression from #1577 

### Lemmy Instance Version

0.18.1-rc.7-75-g90a9b6bd

### Lemmy Instance URL

https://beehaw.org

### PR DESCRIPTION
**Pull request by jsit**
Fixes #1774

## Before

Screenshot 2023-07-03 at 12 29 08 PM

## After

Screenshot 2023-07-03 at 12 26 22 PM

### CODE REVIEW

**Review by SleeplessOne1917 — CHANGES_REQUESTED** [review]
The file you're importing `dataBsTheme` isn't included in the PR for some reason.

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by dessalines** [comment]
So confused rn. 

- Is this completely overriding everything in `theme.tsx`?
- Why is all this necessary for one button? 
- Why is the data-bs attribute in use, I'd thought we removed all bootstrap javascript? 
- Why is bootstrap-specific javascript necessary for that button styling?
- What about everything

**Comment by jsit** [comment]
This isn't Bootstrap JS; it's our own JS to add an additional attribute to a high-level element.

There are a few things in Bootstrap *CSS* that depend on this attribute selector; for instance if you look in `litely.css` you'll see:

```
[data-bs-theme=dark] .accordion-button::after {
  --bs-accordion-btn-icon: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23f7a278'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
  --bs-accordion-btn-active-icon: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23f7a278'%3e%3cpath fill-rule='evenodd' d='M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e");
}
```

Background SVG images can't have their colors modified by CSS, so the SVG markup itself has to be changed.

**Comment by dessalines** [comment]
Ah my bad. I'm used to seeing those data- selectors only for bootstrap javascript.

**Review by dessalines — APPROVED** [review]

**Comment by jsit** [comment]
> @jsit It seems you have missed the compact theme 🙈

Thank you! There's a fix for this already in the works.

**Comment by OpaqueReptile** [comment]
This seems to cause odd style mixing when the instance is set to the lighty theme, and the user is set to browser default+dark mode browser/os. I am now seeing this upon upgrading to 0.18.1:

image

**Pull request merged**
