### PR TITLE
Swap upvote/downvote arrow icon colors

### PR DESCRIPTION
**Pull request by alectrocute**
Hi all!

Quick PR here to swap upvote/downvote colors. Currently we have `text-info` for upvote and `text-danger` for downvote, when most of us are expecting quite the opposite. I propose we swap these per r*ddit conventions.

Screenshot 2023-06-11 at 11 34 30 PM

Screenshot 2023-06-11 at 11 34 09 PM

Thanks! 🙌

### CODE REVIEW

**Comment by alectrocute** [comment]
I have no idea what's going on with the Prettier step on CI 🤔

**Comment by Nutomic** [comment]
Lemmy is not Reddit, we dont need to follow everything that they do.

**Comment by krestenlaust** [comment]
> Lemmy is not Reddit, we dont need to follow everything that they do.

This as well, but we could consider changing the colors or shade of the colors, because right now the colors are basically the same as default reddit but opposite.

This should probably be discussed further in an issue instead of a PR

**Comment by SleeplessOne1917** [comment]
#1169 seems related.

**Comment by alectrocute** [comment]
My thinking was/is, if we're using the same colors, we should at least use them in the same way. I'd be happy to turn this PR into one that changes these colors from orangered/blue – How should we proceed?

**Comment by dessalines** [comment]
I don't understand why text-info and text-danger are inadequate, or need to be swapped. Better to just define a new theme with better colors. There's a [theming guide here](https://join-lemmy.org/docs/en/administration/theming.html?highlight=themes#theming-guide)

Or a better longer-term solution, would be #703 , IE to upgrade lemmy-ui to bootstrap v5, use its auto-generation from `scss` files, and set  colors there.

**Comment by alectrocute** [comment]
I like #703. Closing.

**Pull request closed without merging**
