### PR TITLE
Add FeaturedPosts support

### PR DESCRIPTION
**Pull request by makotech222**
See https://github.com/LemmyNet/lemmy/pull/2585

Adds a new 'Pin' icon to pin to Local view

image

Marking as draft, as its still a bit unfinished. 

Also, soliciting feedback on what the Icon should look like. I'm not a fan of both 'pin to community' and 'pin to local' having the same icon. Not sure what other icons are available currently.

### CODE REVIEW

**Comment by makotech222** [comment]
One last design issue I have currently is when to display the 'pin' icon when displaying the post. We can view a Post from multiple places throughout the app, Home, Community, Search, etc. Currently, if a post is 'Featured in Community', it will show the pin icon, even when viewing from outside the community. 

Should we differentiate when viewing a post from multiple places? Should I just display the 'pin' icon if its either community or local featured? 

image

**Comment by makotech222** [comment]
@dessalines tagging you here, sorry if its doubled up. for the question above.

**Comment by makotech222** [comment]
@Nutomic tagging, any thoughts on the two issues above?

**Comment by dessalines** [comment]
Hrm... it doesn't matter to me, but probably not text. Different color pin icons should work, text-primary and text-secondary.

**Comment by makotech222** [comment]
Okay ill try different color pins. How about the other issue? On showing pinned icon?

**Comment by dessalines** [comment]
It pry makes sense to show the community pin, even if you're viewing it from the front page. No need to create rules around when to show it IMO.

**Comment by makotech222** [comment]
Okay, here's text-primary for community feature, text-secondary for local feature:

image

**Comment by dessalines** [comment]
Looks fine to me, but maybe they should be hidden behind the 3-dot menu. Up to you tho.

**Comment by makotech222** [comment]
The three-dot button is already expanded, and the pin icons only show when expanded

**Comment by dessalines** [comment]
Yeah text with icon is fine.

**Comment by makotech222** [comment]
Okay should be ready to go then! Thanks!

**Review by dessalines — APPROVED** [review]
Looks good, thx!

**Pull request merged**
