### PR TITLE
Add shortcut for submitting post

### LINKED ISSUE #1160: Control+enter to post
It's annoying to not have this, almost every major website does, I don't like having to push "post" every time.

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Closes #1160

### CODE REVIEW

**Comment by krestenlaust** [comment]
Does this apply to replies as well?

**Comment by SleeplessOne1917** [comment]
I'll need to test it once the use_http_client_2 branch gets merged, but it should work anywhere the Markdown textarea is used, which includes both posts and comments.

**Review by dessalines — APPROVED** [review]

**Comment by krestenlaust** [comment]
Fixes #1184 then?

**Comment by Daniel15** [comment]
Thank you! I was going to submit a PR for this too, but you beat me to it :D

**Comment by krestenlaust** [comment]
Closes #1163

**Pull request merged**
