### PR TITLE
Reopen PR 1420 Feature add three six and nine months options frontend

### PR DESCRIPTION
**Pull request by c-andy-candies**
This reopens #1420 which was closed by mistake

### CODE REVIEW

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by L3v3L** [comment]
don't stress, you're doing great.
The woodpecker is not passing because of the same situation here:
https://github.com/LemmyNet/lemmy-ui/pull/1345#issuecomment-1599695975

**Comment by L3v3L** [comment]
@dessalines this requires that this repo point to a new version of [LemmyNet/lemmy-js-client](https://github.com/LemmyNet/lemmy-js-client)

**Comment by L3v3L** [comment]
@c-andy-candies once @dessalines has updated the version, you need to send an empty commit to this branch, it will trigger the woodpecker to rerun.

**Review by dessalines — APPROVED** [review]

**Comment by c-andy-candies** [comment]
@L3v3L Do I need to do something else? I thought LemmyNet/lemmy-js-client#153 added the required sorting options

**Comment by L3v3L** [comment]
> @L3v3L Do I need to do something else? I thought [LemmyNet/lemmy-js-client#153](https://github.com/LemmyNet/lemmy-js-client/pull/153) added the required sorting options

They've just updated. 
The issue was: in this repo the package.json was still pointing to an older version of lemmy-js-client. 
Woodpecker should now not complain about that issue. (You will need to trigger a new woodpecker run, either merge the new changes as you've been doing, or commit an empty commit)

**Pull request merged**
