### PR TITLE
Add polling to refresh post comments/get edits.

### LINKED ISSUE #1565: AutoUpdate setting
### Requirements

- [x] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Is it possible to add an AutoUpdate setting to Lemmy? It is annoying for me to have to refresh to see new posts. In my opinion, AutoUpdate should be extended to communities and not just posts.

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
## Description

Fixes #1565. This should update the post/comments on the post page every minute. Interestingly enough, there was already a config value for this set in the utils.

### CODE REVIEW

**Comment by alectrocute** [comment]
Hmm… What are the chances we could re-integrate websockets for stuff like this? Just an idea. Polling is probably fine, too.

**Comment by alectrocute** [comment]
Also, I’m worried about the reloading causing users to lose their scroll position in the comments.

**Comment by SleeplessOne1917** [comment]
> Hmm… What are the chances we could re-integrate websockets for stuff like this?

I think that would be a good idea, with the caveat that the websocket API is limited to things that actually benefit from instantaneous bilateral client-server communication. Things like replies, edits, messages, and live comments would all be well suited to this. I think the old websocket API had a really bad flaw: parity with the REST API. This lead to using websockets for things that it was a bad choice for, like fetching a post, list of posts for the home/community pages, user profiles, etc. I think that's why the pre-0.18.x versions of the UI project had so many annoying bugs, along with being more difficult to maintain.

However, I think polling is a good short to medium term solution.

> Also, I’m worried about the reloading causing users to lose their scroll position in the comments.

I could see that being an issue if we used websockets as well. There is some comfort to be had in the fact that this is only making API requests to update the UI on the client side, not reloading the whole page.

**Comment by makotech222** [comment]
Most users hate the frontend refreshing while they are using the site. At least leave a user setting to disable it.

**Comment by jsit** [comment]
> Most users hate the frontend refreshing while they are using the site. At least leave a user setting to disable it.

I agree. Please don’t do this without users’s consent. It’s already so easy to lose your place.

Would be nice if maybe a toast popped up that said “There is new content. Reload?”

**Comment by Nutomic** [comment]
Fetching this data every second will cause an immense increase in server load, basically a builtin ddos. At least change it to 5 minutes or more. But honestly I dont see the point, if you want to reload the comments just press F5.

**Pull request closed without merging**
