### PR TITLE
Remove `noIndent` prop from comment nodes on person view

### LINKED ISSUE #1486: Comments alignment on user page
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

The comment is stuck to the left bar - no margin. Post and community name are not aligned in a row.

image

### Describe the solution you'd like.

Margin in comment from the left edge, alignment of community and title information.

### Describe alternatives you've considered.

Not applicable.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alectrocute**
Hi Lemdevs!

- Remove `noIndent` prop from comment nodes on person view. Lack of padding looks wrong.

Before:

Screenshot 2023-06-22 at 6 34 42 PM

After:

Screenshot 2023-06-22 at 6 36 11 PM

Resolves #1486.

Thanks!

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
I noticed inbox has the same issue, could you add that there too?

**Comment by alectrocute** [comment]
@dessalines Yee!

**Comment by alectrocute** [comment]
@dessalines Should be good to go.

**Review by dessalines — APPROVED** [review]
I'll let others look too, maybe a case should be made to remove that field entirely.

**Comment by alectrocute** [comment]
It looks like there's possibly usage of it on child comments? The thought of removing it entirely crossed my mind, too.

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by alectrocute** [comment]
@jsit Any thoughts?

**Comment by jsit** [comment]
@alectrocute I've looked around at it and I kind of don't think it's doing anything worthwhile. Probably preceded some recent style change.

**Comment by alectrocute** [comment]
Let’s remove the rest of the prop usage in another PR, when I have time to do some more thorough testing.

**Pull request merged**
