### PR TITLE
Blur SSR by default when content warning is set

### PR DESCRIPTION
**Pull request by matc-pub**

### CODE REVIEW

**Review by SleeplessOne1917 — CHANGES_REQUESTED** [review]
With these changes, if a user has already consented or is logged in, they always get a blurred document sent back to the browser. This is the opposite problem than we were running into originally.

Also, didn't you say you wanted to prevent the browser from downloading NSFW material entirely? Because even if we get the blur working correctly, that NSFW content is still getting downloaded by img tags.

**Comment by SleeplessOne1917** [comment]
The original PR now works if we're trying to go with the blur. It always makes the document returned from the server blurred when appropriate while also not sending a blurred page back to users who are logged in or already consented.

**Comment by matc-pub** [comment]
> With these changes, if a user has already consented or is logged in, they always get a blurred document sent back to the browser. This is the opposite problem than we were running into originally.

There blur would have been removed on the client before the html was fully parsed.
 
> Also, didn't you say you wanted to prevent the browser from downloading NSFW material entirely? Because even if we get the blur working correctly, that NSFW content is still getting downloaded by img tags.

I believe your thinking of this https://github.com/LemmyNet/lemmy/issues/4625 .

**Comment by matc-pub** [comment]
I'm not in any chat.

**Comment by SleeplessOne1917** [comment]
I am so sorry about that. I got you confused with @MV-GH.

**Comment by MV-GH** [comment]
Yeah that was my concern, whether or not the user had consented. The files are already stored.

**Comment by matc-pub** [comment]
With the cookie approach this should be doable by just adding another guard like auth-guard. But it probably needs a page refresh to update the isoData. The error-guard is currently also stuck, once it sees an error, it will see the same error for the next route too.

**Pull request merged**
