### PR TITLE
SSO Support - alternate UI

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
The main difference between this and #2578 - UI wise at least - is the admin tab for managing SSO providers. Before, is was a table of forms. Since the forms had many fields, even 1 or 2 providers caused a lot of cognitive load trying to read through. In this PR, existing providers are in a list with collapsable entries, and their values are listed in a more space-efficient list of key-value pairs. Adding and editing providers is handled with a modal now.

There are stilll several changes that need to be done. Chief among them is the need for translations; best to hold off on merging until those are decided on and provided. There is also the matter of helpful information about adding OAuth providers that I raised in the other PR. I'm unsure what approach would be best here: Little help circles like we use with some fields in other parts of the UI? A link to a learning resource so admins know what the values they're setting do (perhaps privacy portal has a good resource for this, or maybe we can add something about it to the Lemmy docs)? Some combination of both?

cc. @privacyguard

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
The UI seems fine, but I don't know how to test this properly.

And ya we'll have to wait on @privacyguard for the correct i18n translations of these ones: which should get added as a PR to [this file](https://github.com/LemmyNet/lemmy-translations/blob/main/translations/en.json)

**Comment by dessalines** [comment]
> There is also the matter of helpful information about adding OAuth providers that I raised in the other PR. I'm unsure what approach would be best here: Little help circles like we use with some fields in other parts of the UI?

I think linking to an external page describing these would be best.

**Comment by SleeplessOne1917** [comment]
> There are minor UI improvements that could be made such as text overflow.

Where are you seeing the text overflow issues?

> Concerning the use of the Modal to login, it's not very common except by apps that usually have a large number of providers configured. Do we expect Lemmy admins to have 5+ providers configured? Otherwise it would be much cleaner to simply have the providers directly in the page (as a single column under the user/pass login). That said, this is a style preference so you guys should decide on that. We're just giving our opinion.

I am not sure how many providers the average instance would have configured tbh. When there are fewer I agree that that the modal is less clean. The non-modal starts to messier once the number of providers gets big but, as stated, I'm not sure what a realistic number would be. I'm fine not using the modal, though I think they should be in a section with their own heading.

> I think linking to an external page describing these would be best.

Makes sense. We should probably add a page for it to the Lemmy docs before releasing 0.20.0.

> Concerning the translations, is this PR blocked by the translations? Could it wait 2-3 days?

We usually handle translations for a feature as part of the same PR that adds the feature, although strictly speaking it is not. I find that having them be added as part of the same PR makes it easier to track which translations are new in case we forget to add one.

**Review by dessalines — APPROVED** [review]
I'll try to get this deployed to voyager.lemmy.ml soon so we can test it.

**Pull request merged**
