### PR TITLE
Make page for federating with not yet federated instances

### LINKED ISSUE #1217: Make searching for not yet federated communities be done on its own page
### Is your proposal related to a problem?

Currently, the experience for federating with a community on another instance feels like finding a secret in Dark Souls: you feel clever and rewarded for doing it, but it requires picking up on several easy to miss things. Trying to think of this from someone new to Lemmy who's just wrapped their head around what federation is and wants to try federating with a community that's not available on their instance yet, there isn't an easy way to figure out what to do. The current options for finding this out are:

1. **Word of mouth.** There will likely be several posts about how to do this by devs and instance admins preparing for the reddit exodus, but those instructional posts will only be around for so long.
2. **The blurb on a community sidebar.** This blurb is easy to miss on mobile, where the sidebar is collapsed by default.

### Describe the solution you'd like.

To make it clearer to users that this feature exists and they should be using it, I propose putting searching for not yet federated communities on its own page. This should only require a change on the UI because the regular search and resolve object are already separate endpoints on the API.

### Describe alternatives you've considered.

Putting information on how to use the feature in a hard to miss place.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
## Description

Fixed #1217 

## Screenshots

Federate Page

### CODE REVIEW

**Comment by alectrocute** [comment]
I love that we're addressing this UX issue, but I think we need to think out the UI more. I'm still confused. :/

**Comment by SleeplessOne1917** [comment]
> ...we need to think out the UI more. I'm still confused. :/

What in particular is confusing? I'm trying to make this less confusing than the current way of doing it, so the easier to understand, the better.

**Comment by Nutomic** [comment]
So with this users would have to enter the community name and instance domain seperately? Whats wrong with entering `https://lemmy.ml/c/memes` as a whole? This has multiple advantages, it also works with other things like posts, users and comments. And it works with objects from other platforms which might use a different url format.

**Comment by SleeplessOne1917** [comment]
The remote follow definitely seems better. I'll take a look at the spec.

**Pull request closed without merging**
