### PR TITLE
Fix entire app breaking if routing away from User Settings page

### PR DESCRIPTION
**Pull request by alectrocute**
Hi Lemdevs,

Looks like my last PR was only the tip of the iceberg: https://github.com/LemmyNet/lemmy-ui/pull/1506

https://github.com/LemmyNet/lemmy-ui/pull/1506#issuecomment-1603529191

I only fixed it for Settings -> Home, but not for all the other routes. 💀 On 0.18, it's pretty bad.

- Why are we conditionally loading data based on `!this.state.isIsomorphic`? When routing away from the User Settings page, that condition is definitely falsey.

- I added optional chaining, and added only what was needed as per console errors.

Thanks!

### CODE REVIEW

**Comment by alectrocute** [comment]
https://github.com/LemmyNet/lemmy-ui/assets/35377827/151e17ea-e696-4bff-9509-66750443d0ae

**Comment by SleeplessOne1917** [comment]
The `!isIsomorphic` check is because I only want fetches to be done on mount if content was not already fetched on the server. Perhaps a better name would be something like `didFetchOnServer`.

**Comment by alectrocute** [comment]
> The `!isIsomorphic` check is because I only want fetches to be done on mount if content was not already fetched on the server. Perhaps a better name would be something like `didFetchOnServer`.

We must have something gravely broken in this logic. I feel like this PR is more of a bandaid fix. Any ideas to make it less of one?

**Comment by SleeplessOne1917** [comment]
Closing in favor of #1528

**Pull request closed without merging**
