### PR TITLE
feat: Move advanced post menu into dropdown

### PR DESCRIPTION
**Pull request by jsit**
Rather than having all those "advanced"/"more" buttons for a post in a horizontally-expanding row (which causes content to move around and causes the row to wrap, making the context of the buttons confusing), I've here tucked them away into a dropdown menu.

## Before
Screenshot 2023-06-17 at 6 05 25 PM
Screenshot 2023-06-17 at 6 05 17 PM

## After

Screenshot 2023-06-17 at 6 03 33 PM
Screenshot 2023-06-17 at 6 02 35 PM

### CODE REVIEW

**Comment by Zetaphor** [comment]
Looks like the localization needs some capitalization for delete and lock

**Comment by jsit** [comment]
@Zetaphor Thanks, I have that in a PR at LemmyNet/lemmy-translations#66

**Comment by alectrocute** [comment]
Looks great! Is it possible to make the padding on the X axis match the padding on the Y? The hover background directly touches the side of the element with rounded borders, it’s a little wonky. Other than that, plus the capitalization mentioned by @SleeplessOne1917, this is a really good change I can’t wait to use!

**Comment by jsit** [comment]
@alectrocute I have:

1. Removed the border-radius from the dropdown menu buttons
2. Vertically centered the icon and text inside the buttons

I'm just using the native padding that comes from the `.btn` class, and personally I'd rather stick with the padding Bootstrap gives us for buttons here.

In fact I think they will work better as `.btn-sm`, so I've added that class too. Let me know what you think of this:

Screenshot 2023-06-17 at 9 06 05 PM

**Comment by alectrocute** [comment]
Looks great @jsit!

**Comment by jsit** [comment]
Upon looking closer I see that translations are handled through Weblate, so I'm not sure that PR of mine over there will do any good. Would love to get this merged in even with the lowercase words since it shifts things around quite a bit and don't want to run into a merge conflict later.

**Comment by SleeplessOne1917** [comment]
@alectrocute it was @Zetaphor who pointed out the caps thing lol.

**Review by SleeplessOne1917 — APPROVED** [review]

**Pull request merged**
