### PR TITLE
Fix data-bs-theme

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
## Description

`data-bs-theme` wasn't being set as expected. This change should fix that.

### CODE REVIEW

**Comment by jsit** [comment]
Hm, it was working fine for me? Adding a prop to `<App>` feels odd to me.

**Comment by jsit** [comment]
Also thanks for grabbing those extra themes in the list, I thought I pushed that change but I guess it didn’t make it in.

**Comment by SleeplessOne1917** [comment]
> Hm, it was working fine for me?

When I test the latest changes locally, dark themes always have the upload button with light text on a light background.

> Adding a prop to <App> feels odd to me.

Agreed. This is a kludge. Even with this, it will only work after refreshing the page. We'll need to find a way to make sure the value that gets passed to `data-bs-theme` changes when the user changes.

**Comment by jsit** [comment]
> > Hm, it was working fine for me?
> 
> When I test the latest changes locally, dark themes always have the upload button with light text on a light background.

It works fine for me on page refresh.

**Comment by SleeplessOne1917** [comment]
> It works fine for me on page refresh.

@alectrocute @dessalines does it work for either of you?

**Review by dessalines — APPROVED** [review]

**Pull request merged**
