### PR TITLE
Add `darkly-pureblack` theme

### PR DESCRIPTION
**Pull request by alectrocute**
Hi Lemdevs!

In this PR:

- Add a `darkly-pureblack` theme intended for OLED displays

Screenshot 2023-06-26 at 10 36 35 AM
Screenshot 2023-06-26 at 10 36 38 AM
Screenshot 2023-06-26 at 10 36 47 AM
Screenshot 2023-06-26 at 10 36 49 AM

Thanks!

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
Just tested and it looks beautiful. 

The dropdown's and icons all look fine to me.

**Comment by jsit** [comment]
@alectrocute 

> The only thing I noticed that's broken is the dropdown icon. I'd love to get some more eyeballs on this.

Which dropdown icon? How is it broken?

**Comment by alectrocute** [comment]
> @alectrocute
> 
> > The only thing I noticed that's broken is the dropdown icon. I'd love to get some more eyeballs on this.
> 
> Which dropdown icon? How is it broken?

The down carot icon, I believe it’s implemented via `background-image`.

**Comment by alectrocute** [comment]
> > @alectrocute
> > > The only thing I noticed that's broken is the dropdown icon. I'd love to get some more eyeballs on this.
> > 
> > 
> > Which dropdown icon? How is it broken?
> 
> The down carot icon, I believe it’s implemented via `background-image`.

Forgot to mention that it’s broken because the color matches the background color of the select field, rendering it invisible.

**Comment by alectrocute** [comment]
Fixed it, @dessalines @jsit. The down carot icon is now subtle but visible.

Screenshot 2023-06-27 at 11 30 44 AM

**Comment by jsit** [comment]
Oh, in "select a community"?

**Comment by alectrocute** [comment]
@jsit This one:

Screenshot 2023-06-27 at 11 45 03 AM

I'm pretty sure it's shared across all dropdown selects.

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by jsit** [comment]
Hm, I *think* there might be a way around this. Hold please.

**Comment by jsit** [comment]
So, Bootstrap can change the background image on certain elements by looking for `[data-bs-theme="dark"]`.

If you really want, you can add something like this to `app.tsx`:

```

**Comment by jsit** [comment]
Or you could try:

```tsx
<div id="app"
            data-bs-theme={
              window.matchMedia("(prefers-color-scheme: dark)") ||
              (user &&
                ["darkly", "darkly-red", "darkly-pureblack"].includes(
                  user.local_user_view.local_user.theme
                ))
                ? "dark"
                : "light"
            }
>
```

But `window` is undefined in this context for reasons I don't understand

**Comment by SleeplessOne1917** [comment]
> But window is undefined in this context for reasons I don't understand

Likely because it renders on both the server and the client.

**Comment by jsit** [comment]
Check this out:

`app.tsx`:
```tsx
export class App extends Component<any, any> {
  private isoData: IsoDataOptionalSite = setIsoData(this.context);
  private readonly mainContentRef: RefObject<HTMLElement>;
  constructor(props: any, context: any) {
    super(props, context);
    this.mainContentRef = createRef();
  }

  get isDark() {
    return (
      isBrowser() && window.matchMedia("(prefers-color-scheme: dark)").matches
    );
  }

  handleJumpToContent(event) {
    event.preventDefault();
    this.mainContentRef.current?.focus();
  }
  render() {
    const siteRes = this.isoData.site_res;
    const siteView = siteRes?.site_view;
    const user = UserService.Instance.myUserInfo;

    return (
      <>
        <Provider i18next={I18NextService.i18n}>
          <div
            id="app"
            className="lemmy-site"
            data-test={user?.local_user_view.local_user.theme}
            data-bs-theme={
              (this.isDark &&
                user?.local_user_view.local_user.theme === "browser") ||
              (user &&
                ["darkly", "darkly-red", "darkly-pureblack"].includes(
                  user.local_user_view.local_user.theme
                ))
                ? "dark"
                : "light"
            }
          >
```

**Comment by SleeplessOne1917** [comment]
I think we could extract the logic for determining to use theme light or dark into a function. It shouldn't even need to reference the App component.

**Comment by jsit** [comment]
Oh for sure, I was just throwing it in there to demo it

**Pull request merged**
