### PR TITLE
Community visibility setting

### LINKED ISSUE #2365: Add community.visibility setting
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I'll handle this in a min.

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Closes #2365.

This only adds a setting to the create and edit community forms. Unsure if I should also add some publicly visible indicator indicating that the community is local only.

### CODE REVIEW

**Comment by Nutomic** [comment]
Yes there should be an indicator too, but not sure how that would look like. Maybe a crossed out Fediverse icon?

**Comment by dessalines** [comment]
I'd say even the full text of the visibility type is fine, on the community sidebar.

**Comment by SleeplessOne1917** [comment]
This is what it looks like:
Public screenshot
Local only screenshot

**Review by dessalines — APPROVED** [review]
LGTM

**Pull request merged**
