### PR TITLE
Fix isoData can contain user generated content

### PR DESCRIPTION
**Pull request by 0xDEADCADE**

### CODE REVIEW

**Review by SleeplessOne1917 — APPROVED** [review]
Good catch!

**Comment by 0xDEADCADE** [comment]
My local version of Prettier isn't complaining about this source. I don't usually do JS development, so I don't know what exactly could be wrong here. Does anyone else know, maybe @dessalines?

**Review by dessalines — APPROVED** [review]
Thank you!

**Comment by dessalines** [comment]
@0xDEADCADE I'll handle the formatting in one sec.

**Comment by 0xDEADCADE** [comment]
I would recommend doing a release with this fix relatively soon, and urging instance owners to update. The potential impact of this is high (see my Matrix DMs, or for anyone else, once this is in release, ask me at [@deadcade:deadca.de](https://matrix.to/#/@deadcade:deadca.de) on Matrix), and with the new wave of users, it would leave a very bad first impression.

**Pull request merged**
