### PR TITLE
Add open links in new tab

### PR DESCRIPTION
**Pull request by dessalines**
## Description

Supercedes #1546

### CODE REVIEW

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by DetroitLibertyPenguin** [comment]
Am I correct in understanding that this adds an option for individual users' to toggle the ability in a SETTINGS menu whether or not they'd like external hyperlinks to be owned in a new tab/window by default?

**Comment by dessalines** [comment]
Yes

**Comment by projektilski** [comment]
In my case this option does not do anything. Links are still opened in the same tab.

**Comment by dessalines** [comment]
Probably a browser or plugin issue. You'd need to open an issue with how to reproduce.

**Pull request merged**
