### PR TITLE
added litely-compact and darkly-compact - issue 552

### PR DESCRIPTION
**Pull request by dankxiaobong**
Added darkly-compact in relation to issue https://github.com/LemmyNet/lemmy-ui/issues/552
Took a similiar approach as here: https://github.com/LemmyNet/lemmy-ui/pull/1400 albeit due to significant markup hacky af

### Features:
- Reduced .post-listing height from ~100px+ down to ~80px per post
- 1920px Desktop Breakpoint
- Removed user and community icons (.img-icon)

### Preview:
darkly-compact
Screenshot from 2023-06-21 11-17-30
Screenshot from 2023-06-21 13-50-12

litely-compact
Screenshot from 2023-06-21 13-47-38
Screenshot from 2023-06-21 13-49-35

If someone shows me how to connect lemmy-ui to lemmy.ml https://github.com/LemmyNet/lemmy-ui/issues/1153 I'd be able to do comments too. Currently,  I'm not able to post comments on my local instance

### CODE REVIEW

**Comment by Lloir** [comment]
Just to add a comment to this, if you have a custom theme folder set, it'll duplicate in the themes drop down AND cause some issues. Once that's disabled it's all goochi.

But I love this 10/10

**Review by SleeplessOne1917 — APPROVED** [review]
Looks good, although I'll wait until after 0.18 is released to merge this.

**Comment by alectrocute** [comment]
I think if we’re going to make a compact theme variation, we should make it much more compact. This feels like, slightly more compact. Thoughts?

**Comment by dankxiaobong** [comment]
> I think if we’re going to make a compact theme variation, we should make it much more compact. This feels like, slightly more compact. Thoughts?

I absolutely agree that we should go even more compact.

I had these concerns:
- Changing font and icon sizes alters the overall feel of the base theme. Might as well start a new theme instead of a variation
- Decreasing icons sizes and their paddings affects mobile/touchdisplays navigation negatively (@media-queries + bs = no thank)
- Doing rearrangements of elements with current markup and bs utility classes makes it really difficult and feels dirty. And will likely break 
(I read that there's plans to go with tailwind which imo doesn't make it better. @jsit's proposal https://github.com/LemmyNet/lemmy-ui/pull/1371 with a lot flatter markup would make theming a lot easier and more flexible. )

This imo is a good compromise to get something out quick in order to satisfy user demand. 
(Also I was looking for a good first contribution I'm comfortable with. A lot of the other issues on lemmy are way above my dev skills :P)

Is there anything particularly aggravating that needs fixing?

**Pull request merged**
