### PR TITLE
feat: Move text formatting bar above textarea

### PR DESCRIPTION
**Pull request by jsit**
Move test formatting bar above textarea, as per this comment: https://github.com/LemmyNet/lemmy-ui/pull/1288#issuecomment-1592786570

Note that this does this everywhere there is a markdown textarea, including in creating new posts, editing your bio, etc.

Also fixes:
- Create a "box" around the whoel markdown textarea/formatting bar so it's clear what you're formatting
- The "Post" button had a margin-right, not a margin-left as it should have
- Applied stylelint rules
- Fixed `.emoji-picker` selector
- Remove odd "button"-style formatting from language dropdown and its odd fixed/auto width behavior

Screenshot 2023-06-16 at 8 02 22 PM
Screenshot 2023-06-16 at 7 45 38 PM
Screenshot 2023-06-16 at 7 45 31 PM
Screenshot 2023-06-16 at 7 45 26 PM

### CODE REVIEW

**Comment by alectrocute** [comment]
This may be a nitpick, but non-comment-related use cases, when the buttons are on top, it becomes confusing if there’s another input field nearby. 

It would be great to have this functionality controlled by a prop so we can use the bottom’d version in the non-comment-related use cases.

**Comment by jsit** [comment]
@alectrocute I agree. Not sure if adding a top/bottom switch prop is the right solution, or if it just needs a little design work to make the connection more clear.

**Comment by SleeplessOne1917** [comment]
@jsit my gut is leaning towards the latter.

**Comment by alectrocute** [comment]
> @alectrocute I agree. Not sure if adding a top/bottom switch prop is the right solution, or if it just needs a little design work to make the connection more clear.

> @jsit my gut is leaning towards the latter.

I think either would work! 😄

**Comment by jsit** [comment]
@alectrocute @SleeplessOne1917 

I did some design work here:

Screenshot 2023-06-16 at 7 45 26 PM

Screenshot 2023-06-16 at 7 45 31 PM

Screenshot 2023-06-16 at 7 45 38 PM

Screenshot 2023-06-16 at 8 02 22 PM

**Comment by jsit** [comment]
@alectrocute @SleeplessOne1917 

I did some design work:

Screenshot 2023-06-16 at 7 45 26 PM

Screenshot 2023-06-16 at 7 45 31 PM

Screenshot 2023-06-16 at 7 45 38 PM

Screenshot 2023-06-16 at 8 02 22 PM

**Comment by alectrocute** [comment]
Other than the top border-radius of the text area (noticeable in dark theme), looks great IMO!

**Comment by jsit** [comment]
@alectrocute @SleeplessOne1917 

I did some design work:

Screenshot 2023-06-16 at 7 45 26 PM

Screenshot 2023-06-16 at 7 45 31 PM

Screenshot 2023-06-16 at 7 45 38 PM

Screenshot 2023-06-16 at 8 02 22 PM

**Comment by jsit** [comment]
@alectrocute @SleeplessOne1917 

I did some design work:

Screenshot 2023-06-16 at 7 45 26 PM

Screenshot 2023-06-16 at 7 45 31 PM

Screenshot 2023-06-16 at 7 45 38 PM

Screenshot 2023-06-16 at 8 02 22 PM

**Comment by jsit** [comment]
> Other than the top border-radius of the text area (noticeable in dark theme), looks great IMO!

Good call, just fixed that, thanks.

**Review by SleeplessOne1917 — APPROVED** [review]
Looks great!

**Pull request merged**
