### PR TITLE
Adding nofollow to links. Fixes #542

### LINKED ISSUE #542: Add nofollow to outgoing links.
https://lemmy.ml/post/139092/comment/104521

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
Does this also set nofollow for links which are in markdown? Like post body, comment body, community/user description. I think those are the most important ones (besides post links).

**Comment by dessalines** [comment]
No, but I don't have time to do that right now, as it would require manipulating the markdown-it plugin.

**Comment by Nutomic** [comment]
Okay, then lets keep the issue open until its fully implemented.

**Comment by Nutomic** [comment]
Damn i meant to merge this PR, now there are conflicts :(

**Comment by dessalines** [comment]
I'll get em.

**Comment by Nutomic** [comment]
CI fails for some reason.

**Pull request merged**
