### PR TITLE
Fix infinite spinner for login that results in failure

### PR DESCRIPTION
**Pull request by ayan4m1**
Animation

Added error handling to the login form, so it doesn't just "spin infinitely" when there is an error. Error is surfaced as a toast using existing code, just calling i.setState() in the catch block.

### CODE REVIEW

**Comment by SleeplessOne1917** [comment]
Your code looks good, but I'm confused as to why the exception isn't already being captured in the API wrapper and returning a result with state = failed.

**Comment by ayan4m1** [comment]
Does this help at all?

Screenshot 2023-06-15 094951

**Comment by SleeplessOne1917** [comment]
Here's some relevant code:
```typescript
class WrappedLemmyHttpClient {
  #client: LemmyHttp;

  constructor(client: LemmyHttp) {
    this.#client = client;

    for (const key of Object.getOwnPropertyNames(
      Object.getPrototypeOf(this.#client)
    )) {
      if (key !== "constructor") {
        WrappedLemmyHttpClient.prototype[key] = async (...args) => {
          try {
            const res = await this.#client[key](...args);

            return {
              data: res,
              state: "success",
            };
          } catch (error) {
            console.error(`API error: ${error}`);
            toast(i18n.t(error), "danger");
            return {
              state: "failed",
              msg: error,
            };
          }
        };
      }
    }
  }
}
```

Even though `console.error` is called in the catch block and an error toast is displayed, the client should still return a a `RequestState` object.

**Comment by ayan4m1** [comment]
@SleeplessOne1917 I have updated the code to address your points, take a look when you can?

**Review by dessalines — APPROVED** [review]
Ahh thanks for this one, sry I missed it!

**Pull request merged**
